# Generated by Django 5.2.7 on 2026-03-26 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('items', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('quantity_expected', models.PositiveIntegerField(default=1)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('disposition_status', models.CharField(default='PENDING', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('inventory_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositions', to='inventory.inventoryposition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('return_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='returns.returnline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rma_number', models.CharField(max_length=64)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='returnline',
            name='return_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returnorder'),
        ),
        migrations.AddConstraint(
            model_name='returnorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'rma_number'), name='returns_rma_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.UniqueConstraint(fields=('return_order', 'line_number'), name='returns_line_order_number_uniq'),
        ),
    ]
