# Generated by Django 5.2.7 on 2026-03-26 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('lpn', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('quantity_allocated', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='AVAILABLE', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_positions', to='items.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_positions', to='warehouse.location')),
                ('lpn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='lpn.lpn')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_movements', to='warehouse.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='items.item')),
                ('lpn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='lpn.lpn')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_movements', to='warehouse.location')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventoryposition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='inventoryposition',
            index=models.Index(fields=['tenant', 'item', 'status'], name='inventory_i_tenant__73ce86_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryposition',
            index=models.Index(fields=['tenant', 'expiry_date'], name='inventory_i_tenant__e48bc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryposition',
            constraint=models.UniqueConstraint(fields=('tenant', 'lpn', 'location'), name='inventory_position_tenant_lpn_location_uniq'),
        ),
    ]
