# Generated by Django 5.2.7 on 2026-03-26 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('lpn', '0001_initial'),
        ('tenants', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=64)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='InboundLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('qty_expected', models.PositiveIntegerField()),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('requires_lot', models.BooleanField(default=False)),
                ('requires_expiry', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_lines', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inbound.inboundorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('operator_id', models.CharField(blank=True, max_length=64)),
                ('inbound_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_events', to='inbound.inboundline')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_events', to='warehouse.location')),
                ('lpn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_events', to='lpn.lpn')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='inboundorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='inbound_order_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboundline',
            constraint=models.UniqueConstraint(fields=('inbound_order', 'line_number'), name='inbound_line_order_line_number_uniq'),
        ),
    ]
