# Generated by Django 5.2.7 on 2026-03-26 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='America/Toronto', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(default='GENERAL', max_length=30)),
                ('temp_controlled', models.BooleanField(default=False)),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('aisle', models.CharField(db_index=True, max_length=10)),
                ('bay', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('location_type', models.CharField(default='PICK_FACE', max_length=20)),
                ('storage_strategy', models.CharField(default='FLOATING', max_length=20)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_volume_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_units', models.PositiveIntegerField(blank=True, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_lift', models.BooleanField(default=False)),
                ('sort_sequence', models.IntegerField(db_index=True, default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='warehouse.zone')),
            ],
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='warehouse_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='warehouse_zone_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='warehouse_location_zone_code_uniq'),
        ),
    ]
