FROM python:3.13-slim

WORKDIR /app

COPY requirements /tmp/requirements
RUN pip install --no-cache-dir -r /tmp/requirements/development.txt

COPY . /app

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

