# Generated by Django 5.2.7 on 2026-03-26 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('items', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=64)),
                ('status', models.CharField(default='RECEIVED', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_allocated', models.PositiveIntegerField(default=0)),
                ('quantity_picked', models.PositiveIntegerField(default=0)),
                ('quantity_packed', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='items.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='outbound.outboundorder')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_number', models.CharField(max_length=64)),
                ('container_type', models.CharField(default='CARTON', max_length=30)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('quantity_packed', models.PositiveIntegerField(default=0)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='outbound.outboundorder')),
            ],
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wave_number', models.CharField(max_length=64)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('release_notes', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_number', models.CharField(max_length=64)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('quantity_to_pick', models.PositiveIntegerField()),
                ('quantity_picked', models.PositiveIntegerField(default=0)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_tasks', to=settings.AUTH_USER_MODEL)),
                ('inventory_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='inventory.inventoryposition')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='outbound.orderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='outbound.wave')),
            ],
        ),
        migrations.CreateModel(
            name='WaveOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_orders', to='outbound.outboundorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_orders', to='outbound.wave')),
            ],
        ),
        migrations.AddConstraint(
            model_name='outboundorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='outbound_order_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('outbound_order', 'line_number'), name='outbound_order_line_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='container',
            constraint=models.UniqueConstraint(fields=('tenant', 'container_number'), name='outbound_container_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='wave',
            constraint=models.UniqueConstraint(fields=('tenant', 'wave_number'), name='outbound_wave_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='picktask',
            constraint=models.UniqueConstraint(fields=('tenant', 'task_number'), name='outbound_pick_task_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='waveorder',
            constraint=models.UniqueConstraint(fields=('wave', 'outbound_order'), name='outbound_wave_order_uniq'),
        ),
    ]
