# Generated by Django 5.2.7 on 2026-03-26 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outbound', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(max_length=64)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('carrier_name', models.CharField(blank=True, max_length=128)),
                ('service_level', models.CharField(blank=True, max_length=64)),
                ('tracking_number', models.CharField(blank=True, max_length=128)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='outbound.container')),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='outbound.outboundorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest_number', models.CharField(max_length=64)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('shipments', models.ManyToManyField(blank=True, related_name='manifests', to='shipping.shipment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('tenant', 'shipment_number'), name='shipping_shipment_tenant_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='manifest',
            constraint=models.UniqueConstraint(fields=('tenant', 'manifest_number'), name='shipping_manifest_tenant_number_uniq'),
        ),
    ]
