# Generated by Django 5.2.7 on 2026-03-26 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('gtin', models.CharField(blank=True, db_index=True, max_length=14)),
                ('upc', models.CharField(blank=True, max_length=12)),
                ('description_en', models.CharField(max_length=300)),
                ('description_fr', models.CharField(blank=True, max_length=300)),
                ('unit_of_measure', models.CharField(default='EA', max_length=20)),
                ('units_per_inner', models.PositiveIntegerField(default=1)),
                ('units_per_case', models.PositiveIntegerField(default=1)),
                ('cases_per_pallet', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('lot_controlled', models.BooleanField(default=False)),
                ('serial_tracked', models.BooleanField(default=False)),
                ('expiry_tracked', models.BooleanField(default=False)),
                ('catch_weight', models.BooleanField(default=False)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sku'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sku'), name='items_tenant_sku_uniq')],
            },
        ),
    ]
